import { SwordConfig } from "../types";

export const SWORDS_ARSENAL: SwordConfig[] = [
  {
    id: "muramasa",
    name: "Muramasa Bloodforged",
    japaneseName: "妖刀村正 (Cursed Bloodforged)",
    kanjiSymbol: "血",
    lore: "Forged in the fires of vengeance. The blade hungers for justice and monomolecular precision, severing corrupted data packets instantly.",
    quote: "No firewall withstands the thirst of Muramasa.",
    sheathColor: "#1a0505",
    sheathAccent: "#dc2626",
    bladeTint: "#ef4444",
    tsubaStyle: "Crimson Four-Petal Crest",
    element: "blood",
    sliceColor: "#ff0033",
    auraGlow: "rgba(239, 68, 68, 0.8)",
    powerRating: 98,
    speedRating: 92,
    defenseRating: 85,
    integritySeal: "SEAL-MURAMASA-001-ALPHA"
  },
  {
    id: "masamune",
    name: "Masamune Serenity",
    japaneseName: "名物正宗 (Sacred Tranquility)",
    kanjiSymbol: "正",
    lore: "The peaceful holy blade crafted by Gorō Nyūdō Masamune. It cuts only malice, leaving innocent threads and verified code unblemished.",
    quote: "True mastery needs only a single silent stroke.",
    sheathColor: "#0b192c",
    sheathAccent: "#38bdf8",
    bladeTint: "#e0f2fe",
    tsubaStyle: "Lotus of Pure Dharma",
    element: "frost",
    sliceColor: "#38bdf8",
    auraGlow: "rgba(56, 189, 248, 0.8)",
    powerRating: 94,
    speedRating: 97,
    defenseRating: 99,
    integritySeal: "SEAL-MASAMUNE-002-BETA"
  },
  {
    id: "kusanagi",
    name: "Kusanagi-no-Tsurugi",
    japaneseName: "草薙の剣 (Grass-Cutting Divine Blade)",
    kanjiSymbol: "神",
    lore: "One of the Three Imperial Regalia of Japan. Unearthed from the eighth tail of Yamata-no-Orochi, channeler of celestial tempest winds.",
    quote: "The sovereign tempest clears all deception.",
    sheathColor: "#1c1917",
    sheathAccent: "#eab308",
    bladeTint: "#fef08a",
    tsubaStyle: "Imperial Eight-Fold Seal",
    element: "divine",
    sliceColor: "#facc15",
    auraGlow: "rgba(234, 179, 8, 0.85)",
    powerRating: 99,
    speedRating: 95,
    defenseRating: 96,
    integritySeal: "SEAL-KUSANAGI-003-REGALIA"
  },
  {
    id: "shadow_shinobi",
    name: "Shadow Dragon Shinobi-to",
    japaneseName: "影龍忍刀 (Silent Shadow Edge)",
    kanjiSymbol: "影",
    lore: "A straight-bladed ninjato crafted with light-absorbent obsidian alloys. Emits zero telemetry, ideal for stealth verification and air-gapped security.",
    quote: "Silence is the sharpest perimeter.",
    sheathColor: "#09090b",
    sheathAccent: "#52525b",
    bladeTint: "#a1a1aa",
    tsubaStyle: "Square Iron Stealth Guard",
    element: "shadow",
    sliceColor: "#71717a",
    auraGlow: "rgba(113, 113, 122, 0.8)",
    powerRating: 91,
    speedRating: 100,
    defenseRating: 88,
    integritySeal: "SEAL-SHINOBI-004-STEALTH"
  },
  {
    id: "cyberpunk_neon",
    name: "Cyberpunk Neon Plasma",
    japaneseName: "電磁サイバー刀 (Plasma Monomolecular)",
    kanjiSymbol: "電",
    lore: "Infused with high-frequency electromagnetic plasma coils. Melts through brute-force attacks and cryptographic anomalies in nanoseconds.",
    quote: "Current flowing at 40 gigavolts per strike.",
    sheathColor: "#0d0221",
    sheathAccent: "#ec4899",
    bladeTint: "#06b6d4",
    tsubaStyle: "Cyber Heatsink Mesh",
    element: "plasma",
    sliceColor: "#ec4899",
    auraGlow: "rgba(236, 72, 153, 0.85)",
    powerRating: 96,
    speedRating: 96,
    defenseRating: 90,
    integritySeal: "SEAL-CYBER-005-PLASMA"
  },
  {
    id: "void_cleaver",
    name: "Void Cleaver Nodachi",
    japaneseName: "虚空大太刀 (Dark Matter Edge)",
    kanjiSymbol: "虚",
    lore: "A two-meter monumental field nodachi folded from cosmic singularity fragments. Warps the fabric of memory spaces into impenetrable cryptographic vaults.",
    quote: "Beyond the event horizon, truth remains inviolate.",
    sheathColor: "#120824",
    sheathAccent: "#a855f7",
    bladeTint: "#c084fc",
    tsubaStyle: "Cosmic Eclipse Disk",
    element: "void",
    sliceColor: "#a855f7",
    auraGlow: "rgba(168, 85, 247, 0.85)",
    powerRating: 100,
    speedRating: 84,
    defenseRating: 94,
    integritySeal: "SEAL-VOID-006-NODACHI"
  },
  {
    id: "shogun_gold",
    name: "Shogun Gold Damascus",
    japaneseName: "将軍金波刀 (Imperial Gold Wave)",
    kanjiSymbol: "覇",
    lore: "Folded 100,000 times in gold-infused tamahagane steel. The crest of supreme command authorized exclusively by Scott Gushea.",
    quote: "Authority sealed in gold and discipline.",
    sheathColor: "#291800",
    sheathAccent: "#f59e0b",
    bladeTint: "#fde68a",
    tsubaStyle: "Golden Chrysanthemum Emblem",
    element: "gold",
    sliceColor: "#fbbf24",
    auraGlow: "rgba(245, 158, 11, 0.85)",
    powerRating: 95,
    speedRating: 91,
    defenseRating: 98,
    integritySeal: "SEAL-SHOGUN-007-GUSHEA"
  },
  {
    id: "crimson_lotus",
    name: "Crimson Lotus Wakizashi",
    japaneseName: "紅蓮蓮華 (Blazing Defense Wakizashi)",
    kanjiSymbol: "蓮",
    lore: "A swift companion blade carried inside the obi sash. Bursts into crimson sakura fire on quick-draw to parry zero-day memory exploits.",
    quote: "A shield disguised as a blossom.",
    sheathColor: "#2b0a12",
    sheathAccent: "#f43f5e",
    bladeTint: "#fda4af",
    tsubaStyle: "Petal Guard of the Sacred Phoenix",
    element: "fire",
    sliceColor: "#f43f5e",
    auraGlow: "rgba(244, 63, 94, 0.85)",
    powerRating: 89,
    speedRating: 99,
    defenseRating: 95,
    integritySeal: "SEAL-LOTUS-008-WAKIZASHI"
  },
  {
    id: "thunderstrike_raijin",
    name: "Thunderstrike Raijin",
    japaneseName: "雷神霆刃 (Thunder God Arc)",
    kanjiSymbol: "雷",
    lore: "Forged on the stormy peak of Mount Fuji. Channels localized lightning storms through carbonite capacitors, shocking any unauthorized intruder.",
    quote: "Strike like thunder, leave no trace.",
    sheathColor: "#042f2e",
    sheathAccent: "#14b8a6",
    bladeTint: "#5eead4",
    tsubaStyle: "Triple Tomoe Thunder Drum",
    element: "lightning",
    sliceColor: "#2dd4bf",
    auraGlow: "rgba(20, 184, 166, 0.85)",
    powerRating: 97,
    speedRating: 98,
    defenseRating: 87,
    integritySeal: "SEAL-RAIJIN-009-STORM"
  },
  {
    id: "ghost_flame_oni",
    name: "Ghost Flame Oni-Slayer",
    japaneseName: "幽鬼炎切 (Spectral Exorcism Blade)",
    kanjiSymbol: "鬼",
    lore: "Bathed in cold spectral cyan ghost flames. Exorcises malicious ghost processes, zombie background scripts, and unsolicited memory injections.",
    quote: "Even ghosts bow to sovereign discipline.",
    sheathColor: "#031e17",
    sheathAccent: "#10b981",
    bladeTint: "#6ee7b7",
    tsubaStyle: "Demon Mask Horned Guard",
    element: "spirit",
    sliceColor: "#10b981",
    auraGlow: "rgba(16, 185, 129, 0.85)",
    powerRating: 96,
    speedRating: 94,
    defenseRating: 93,
    integritySeal: "SEAL-ONI-010-SPECTRAL"
  }
];
